### PR TITLE
#2 Add Reyna support

### PR DESCRIPTION
**Pull request by phillipse01**
* #2 Added new icons and images for the new character Reyna. Updated agents.js to add Reyna support.
* #3 Updated icons to more closely resemble the in-game equivelent. Reyna was hard to find, so defaulted to the screencapture approach.

### CODE REVIEW

**Comment by andrerfcsantos** [comment]
Hey,

First of all, thanks for the pull request.

Haven't followed the news around the game lately and didn't realize a new hero was released, thanks for bringing this to my attention.

About the merge request:

1) The change to agents.js is correct :)
2) The portrait image should be named in lower case, like the others. So `Reyna.png` should be `reyna.png`. This is because the code is specifically looking for lowercase images: https://github.com/andrerfcsantos/valorant-agent-picker/blob/a8561b89f23157428eb3d2f29eec7b6b41144460/src/pages/PickerContent.vue#L29
3) What was the source of your images?
4) I was previously using the images from the wiki: 
- https://valorant.fandom.com/wiki/Category:Agent_Images
- https://valorant.fandom.com/wiki/Category:Agent_Icons
There's an icon and portrait for Reyna there, no need for screencap. For consistency and ease of future updates, i would rather have the images come from only 1 source, 2 if really necessary, and avoid screencaps.

**Comment by phillipse01** [comment]
Cheers for the info!

Didn’t know the original source so I got it direct from the game. Would you like me to revert the icon change to the wiki ones again?

Thanks for the catch on the portrait name! Will update

**Comment by andrerfcsantos** [comment]
Hey,

Yes, please revert the images to the ones of the wiki too (even if they are not the new ones), just add reyna portrait and icon from the wiki too.

I want the site to eventually be updated with the new icons, but that's something that can be dealt with later, when there is a reliable source for those images.

As soon as you do that I'll merge and deploy :)

**Comment by phillipse01** [comment]
Reverted icons and added the wiki one for Reyna - there was no half portrait wiki photo for Reyna so I keep the existing for consistency. Let me know if this is ok!

**Comment by andrerfcsantos** [comment]
That's perfect,
Merged and deployed to the site.

Thanks for taking the time to submit this.

I'll let #3 open for now.

**Comment by phillipse01** [comment]
Cheers!

**Pull request merged**
